---
volumes:
  ubuntu-xfce_data: {}

# https://hub.docker.com/r/linuxserver/webtop
# https://www.linuxserver.io/blog/2021-05-05-meet-webtops-a-linux-desktop-environment-in-your-browser
services:
  ubuntu-xfce:
    # image: lscr.io/linuxserver/webtop:ubuntu-icewm
    # image: lscr.io/linuxserver/webtop:ubuntu-openbox
    # image: lscr.io/linuxserver/webtop:ubuntu-i3
    # image: lscr.io/linuxserver/webtop:ubuntu-kde
    # image: lscr.io/linuxserver/webtop:ubuntu-mate
    # image: lscr.io/linuxserver/webtop:latest
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    # security_opt:
    #   - seccomp:unconfined #optional
    hostname: media-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=XFCE-Ubuntu-Media-Server
    volumes:
      - ubuntu-xfce_data:/config
      - ./jellyfin.sh:/usr/local/bin/jellyfin-setup.sh
      - ./movies.sh:/usr/local/bin/movies.sh
      - ./series.sh:/usr/local/bin/series.sh
    ports:
      - 3007:3000 # UI for linux
      - 8096:8096 # Jellyfin server
      - 8097:8080 # For file browser
    shm_size: "1gb"
    # devices:
    #   - /dev/dri:/dev/dri #optional
    restart: unless-stopped
